spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{ip}:3306/ttms?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  web:
    resources:
      static-locations: /

server:
  port : 9090
  servlet:
    context-path: /
  address: 0.0.0.0

logging:
  level:
    org:
      springframework:
        web: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning


  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置统一的主键生成策略
      id-type: auto
  type-aliases-package: com.ttms.pojo
  mapper-locations: classpath*:com/ttms/**/*.xml

